# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/fifo_0/fifo_0.xci
# IP: The module: 'fifo_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/PC/Desktop/fec_verf/prj/fec_lasercom/fec_lasercom.gen/fifo_0/ip/fifo_0/fifo_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/PC/Desktop/fec_verf/prj/fec_lasercom/fec_lasercom.gen/fifo_0/ip/fifo_0/fifo_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/PC/Desktop/fec_verf/prj/fec_lasercom/fec_lasercom.gen/fifo_0/ip/fifo_0/fifo_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: ip/fifo_0/fifo_0.xci
# IP: The module: 'fifo_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/PC/Desktop/fec_verf/prj/fec_lasercom/fec_lasercom.gen/fifo_0/ip/fifo_0/fifo_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/PC/Desktop/fec_verf/prj/fec_lasercom/fec_lasercom.gen/fifo_0/ip/fifo_0/fifo_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/PC/Desktop/fec_verf/prj/fec_lasercom/fec_lasercom.gen/fifo_0/ip/fifo_0/fifo_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
