# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/rs_decoder_0/rs_decoder_0.xci
# IP: The module: 'rs_decoder_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/PC/Desktop/fec_verf/prj/fec_lasercom/fec_lasercom.gen/rs_decoder_0/ip/rs_decoder_0/rs_decoder_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rs_decoder_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: ip/rs_decoder_0/rs_decoder_0.xci
# IP: The module: 'rs_decoder_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/PC/Desktop/fec_verf/prj/fec_lasercom/fec_lasercom.gen/rs_decoder_0/ip/rs_decoder_0/rs_decoder_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'rs_decoder_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
