# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/gtwizard_ultrascale_0/gtwizard_ultrascale_0.xci
# IP: The module: 'gtwizard_ultrascale_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/PC/Desktop/fec_verf/prj/fec_lasercom/fec_lasercom.gen/gtwizard_ultrascale_0/ip/gtwizard_ultrascale_0/synth/gtwizard_ultrascale_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gtwizard_ultrascale_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/PC/Desktop/fec_verf/prj/fec_lasercom/fec_lasercom.gen/gtwizard_ultrascale_0/ip/gtwizard_ultrascale_0/synth/gtwizard_ultrascale_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'gtwizard_ultrascale_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: ip/gtwizard_ultrascale_0/gtwizard_ultrascale_0.xci
# IP: The module: 'gtwizard_ultrascale_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/PC/Desktop/fec_verf/prj/fec_lasercom/fec_lasercom.gen/gtwizard_ultrascale_0/ip/gtwizard_ultrascale_0/synth/gtwizard_ultrascale_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'gtwizard_ultrascale_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/PC/Desktop/fec_verf/prj/fec_lasercom/fec_lasercom.gen/gtwizard_ultrascale_0/ip/gtwizard_ultrascale_0/synth/gtwizard_ultrascale_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'gtwizard_ultrascale_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
