# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/clk_wiz_sys/clk_wiz_sys.xci
# IP: The module: 'clk_wiz_sys' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/PC/Desktop/fec_verf/prj/fec_lasercom/fec_lasercom.gen/clk_wiz_sys/ip/clk_wiz_sys/clk_wiz_sys_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_sys'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/PC/Desktop/fec_verf/prj/fec_lasercom/fec_lasercom.gen/clk_wiz_sys/ip/clk_wiz_sys/clk_wiz_sys.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_sys'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/PC/Desktop/fec_verf/prj/fec_lasercom/fec_lasercom.gen/clk_wiz_sys/ip/clk_wiz_sys/clk_wiz_sys_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_sys'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: ip/clk_wiz_sys/clk_wiz_sys.xci
# IP: The module: 'clk_wiz_sys' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/PC/Desktop/fec_verf/prj/fec_lasercom/fec_lasercom.gen/clk_wiz_sys/ip/clk_wiz_sys/clk_wiz_sys_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_sys'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/PC/Desktop/fec_verf/prj/fec_lasercom/fec_lasercom.gen/clk_wiz_sys/ip/clk_wiz_sys/clk_wiz_sys.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_sys'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: c:/Users/PC/Desktop/fec_verf/prj/fec_lasercom/fec_lasercom.gen/clk_wiz_sys/ip/clk_wiz_sys/clk_wiz_sys_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_sys'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
