# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/PC/Desktop/fec_verf/prj/fec_lasercom/fec_lasercom.runs/synth_tx/fec_tx_fpga_top.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

OPTRACE "synth_tx" START { ROLLUP_AUTO }
set_param general.maxThreads 32
set_param chipscope.maxJobs 8
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xczu15eg-ffvb1156-2-i

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/PC/Desktop/fec_verf/prj/fec_lasercom/fec_lasercom.cache/wt [current_project]
set_property parent.project_path C:/Users/PC/Desktop/fec_verf/prj/fec_lasercom/fec_lasercom.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/PC/Desktop/fec_verf/prj/fec_lasercom/fec_lasercom.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_verilog C:/Users/PC/Desktop/fec_verf/prj/fec_lasercom/fec_lasercom.srcs/sources_1/new/global_defines.vh
read_verilog -library xil_defaultlib {
  C:/Users/PC/Desktop/fec_verf/prj/fec_lasercom/rtl/rs_Deinterleaver_xpm.v
  C:/Users/PC/Desktop/fec_verf/prj/fec_lasercom/rtl/AdditiveScrambler.v
  C:/Users/PC/Desktop/fec_verf/prj/fec_lasercom/rtl/crc32.v
  C:/Users/PC/Desktop/fec_verf/prj/fec_lasercom/rtl/fec_tx.v
  C:/Users/PC/Desktop/fec_verf/prj/fec_lasercom/rtl/fifo_8b_flag_sync.v
  C:/Users/PC/Desktop/fec_verf/prj/fec_lasercom/rtl/fso_framer.v
  C:/Users/PC/Desktop/fec_verf/prj/fec_lasercom/rtl/gearbox_8to32_bs.v
  C:/Users/PC/Desktop/fec_verf/prj/fec_lasercom/rtl/gth_raw_top.v
  C:/Users/PC/Desktop/fec_verf/prj/fec_lasercom/rtl/gtwizard_ultrascale_0_prbs_any.v
  C:/Users/PC/Desktop/fec_verf/prj/fec_lasercom/rtl/rs_encode_frontend.v
  C:/Users/PC/Desktop/fec_verf/prj/fec_lasercom/rtl/rs_interleaver_xpm.v
  C:/Users/PC/Desktop/fec_verf/prj/fec_lasercom/rtl/fec_tx_fpga_top.v
}
read_ip -quiet C:/Users/PC/Desktop/fec_verf/prj/fec_lasercom/fec_lasercom.srcs/rs_encoder_0/ip/rs_encoder_0/rs_encoder_0.xci
set_property used_in_implementation false [get_files -all c:/Users/PC/Desktop/fec_verf/prj/fec_lasercom/fec_lasercom.gen/rs_encoder_0/ip/rs_encoder_0/rs_encoder_0_ooc.xdc]

read_ip -quiet C:/Users/PC/Desktop/fec_verf/prj/fec_lasercom/fec_lasercom.srcs/fifo_0/ip/fifo_0/fifo_0.xci
set_property used_in_implementation false [get_files -all c:/Users/PC/Desktop/fec_verf/prj/fec_lasercom/fec_lasercom.gen/fifo_0/ip/fifo_0/fifo_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/PC/Desktop/fec_verf/prj/fec_lasercom/fec_lasercom.gen/fifo_0/ip/fifo_0/fifo_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/PC/Desktop/fec_verf/prj/fec_lasercom/fec_lasercom.gen/fifo_0/ip/fifo_0/fifo_0_ooc.xdc]

read_ip -quiet C:/Users/PC/Desktop/fec_verf/prj/fec_lasercom/fec_lasercom.srcs/clk_wiz_sys/ip/clk_wiz_sys/clk_wiz_sys.xci
set_property used_in_implementation false [get_files -all c:/Users/PC/Desktop/fec_verf/prj/fec_lasercom/fec_lasercom.gen/clk_wiz_sys/ip/clk_wiz_sys/clk_wiz_sys_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/PC/Desktop/fec_verf/prj/fec_lasercom/fec_lasercom.gen/clk_wiz_sys/ip/clk_wiz_sys/clk_wiz_sys.xdc]
set_property used_in_implementation false [get_files -all c:/Users/PC/Desktop/fec_verf/prj/fec_lasercom/fec_lasercom.gen/clk_wiz_sys/ip/clk_wiz_sys/clk_wiz_sys_ooc.xdc]

read_ip -quiet C:/Users/PC/Desktop/fec_verf/prj/fec_lasercom/fec_lasercom.srcs/async_fifo_32w_32r/ip/async_fifo_32w_32r/async_fifo_32w_32r.xci
set_property used_in_implementation false [get_files -all c:/Users/PC/Desktop/fec_verf/prj/fec_lasercom/fec_lasercom.gen/async_fifo_32w_32r/ip/async_fifo_32w_32r/async_fifo_32w_32r.xdc]
set_property used_in_implementation false [get_files -all c:/Users/PC/Desktop/fec_verf/prj/fec_lasercom/fec_lasercom.gen/async_fifo_32w_32r/ip/async_fifo_32w_32r/async_fifo_32w_32r_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/PC/Desktop/fec_verf/prj/fec_lasercom/fec_lasercom.gen/async_fifo_32w_32r/ip/async_fifo_32w_32r/async_fifo_32w_32r_ooc.xdc]

read_ip -quiet C:/Users/PC/Desktop/fec_verf/prj/fec_lasercom/fec_lasercom.srcs/gtwizard_ultrascale_0/ip/gtwizard_ultrascale_0/gtwizard_ultrascale_0.xci
set_property used_in_implementation false [get_files -all c:/Users/PC/Desktop/fec_verf/prj/fec_lasercom/fec_lasercom.gen/gtwizard_ultrascale_0/ip/gtwizard_ultrascale_0/synth/gtwizard_ultrascale_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/PC/Desktop/fec_verf/prj/fec_lasercom/fec_lasercom.gen/gtwizard_ultrascale_0/ip/gtwizard_ultrascale_0/synth/gtwizard_ultrascale_0.xdc]

OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/PC/Desktop/fec_verf/prj/fec_lasercom/constraints/system_cons.xdc
set_property used_in_implementation false [get_files C:/Users/PC/Desktop/fec_verf/prj/fec_lasercom/constraints/system_cons.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top fec_tx_fpga_top -part xczu15eg-ffvb1156-2-i
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef fec_tx_fpga_top.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
generate_parallel_reports -reports { "report_utilization -file fec_tx_fpga_top_utilization_synth.rpt -pb fec_tx_fpga_top_utilization_synth.pb"  } 
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_tx" END { }
